name: Banner
context:
  text: |
      <p>Drupal 9 is now end of life and unsupported. If you're stuck on Drupal 7, 8 or 9, get unstuck with a <a href="/drupal-upgrade">Drupal upgrade roadmap and upgrade to Drupal 10</a>.</p>
