version: '3.4'

volumes:
  dist:
    driver: local
  node_modules:
    driver: local

services:
  assets:
    build:
      context: .
      target: assets
    tty: true
    volumes:
      - dist:/app/public/dist
      - node_modules:/app/node_modules
      - ./assets:/app/assets
      - ./components:/app/components
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js

  cli:
    build:
      context: .
      target: cli
    tty: true
    volumes:
      - node_modules:/app/node_modules
      - .:/app

  fractal:
    build:
      context: .
      target: fractal
    volumes:
      - dist:/app/public/dist
      - node_modules:/app/node_modules
      - .:/app
    ports:
      - 3000:3000
      - 3002:3002
    depends_on:
      - assets
