title: About the Author
context:
    text: |
        Oliver Davies is a PHP Developer and Linux Systems Administrator based in the UK.
        He is a Senior Software Engineer at <a href="https://inviqa.com?utm_source=oliverdavies.uk&amp;utm_medium=about-author" class="link">Inviqa</a> and a part-time freelancer specialising in Drupal and Symfony application development.
